### PR TITLE
support multiple UCRM installations

### PR DESCRIPTION
**Pull request by keksa**

### CODE REVIEW

**Comment by keksa** [comment]
Hello @oscarmy333, as the netflow port is mapped to UDP, `nc -z` did not work for me, but `nc -zu` did, why do you think it should be changed?

**Comment by oscarmy333** [comment]
Hello My Dear,
nc -uz did not work on Ubuntu 16.04.3, but nc -zu did; thanks for you ask.

**Comment by keksa** [comment]
@oscarmy333 Both are working just fine for me on Ubuntu 16.04.3, did you get any errors when running this?

**Comment by oscarmy333** [comment]
Yes, i did... Getting error when Interface aliasing allows one interface to
have multiple IP addresses.
Thanks for heads-up!

*"Después de escalar una montaña muy alta, descubrimos que hay muchas otras
montañas por escalar."*
-------------------------------------------
*Oscar MENESES YARANGA*
*Cel.RPM  #999545445*
*Movistar: 966182675-969651207*

*AYACUCHO - PERU*

2017-10-20 9:30 GMT-05:00 Ondřej Exner <notifications@github.com>:

**Pull request merged**
